version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
      - AWS_REGION=$AWS_DEFAULT_REGION
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.6/2023-10-17/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - mkdir -p ~/.kube
      - echo Setting up kubeconfig for EKS...
      - aws eks --region ap-northeast-2 update-kubeconfig --name spotrankeks
      - echo Verifying Kubernetes access...
      - kubectl version --client

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 440744225243.dkr.ecr.ap-northeast-2.amazonaws.com
      - echo Pre-build step completed.

  build:
    commands:
      - echo Building and pushing Docker images to spotrank-ecr...
      - echo Building backend service...
      - docker build -t backend:latest .
      - docker tag backend:latest 440744225243.dkr.ecr.ap-northeast-2.amazonaws.com/bbc:backend
      - docker push 440744225243.dkr.ecr.ap-northeast-2.amazonaws.com/bbc:backend

  post_build:
    commands:
      - echo Deploying services to EKS...
      - echo Deploying backend service...
      - sed -i.bak 's#AWS_ECR_URI#440744225243.dkr.ecr.ap-northeast-2.amazonaws.com/bbc:backend#g' ./EKS/deployment.yaml
      - kubectl apply -f ./EKS/deployment.yaml
      - kubectl apply -f ./EKS/service.yaml

      - echo Deployment completed on $(date).

artifacts:
  files:
    - EKS/deployment.yaml
    - EKS/service.yaml
