apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotrank-be-deployment
  namespace: default
  labels:
    app: spotrank-be
    environment: production
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotrank-be
  template:
    metadata:
      labels:
        app: spotrank-be
    spec:
      containers:
        - name: spotrank-be2
          image: 440744225243.dkr.ecr.ap-northeast-2.amazonaws.com/bbc:backend
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: "13.209.87.204"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "Welcome1!"
            - name: DATABASE_NAME
              value: "spotrank"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
