apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotrank-be-deployment
  namespace: default
  labels:
    app: spotrank-be
    environment: production
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotrank-be
  template:
    metadata:
      labels:
        app: spotrank-be
    spec:
      containers:
        - name: spotrank-be2
          image: 440744225243.dkr.ecr.ap-northeast-2.amazonaws.com/bbc:backend
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: "127.0.0.1"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_NAME
              value: "info"
            - name: DATE
              value: 'DATE_STRING'
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            - name: git-lfs-cache
              mountPath: /app/git-lfs-cache
      volumes:
        - name: git-lfs-cache
          emptyDir: {}
